const phrases = [
    {"english": "I love cooking Italian food.", "portuguese": ["Eu adoro cozinhar comida italiana.", "Amo fazer pratos italianos."]},
    {"english": "Can you pass me the salt?", "portuguese": ["Você pode me passar o sal?", "Passa o sal, por favor?"]},
    {"english": "What is the recipe for this dish?", "portuguese": ["Qual é a receita deste prato?", "Como se faz esse prato?"]},
    {"english": "I need to buy some ingredients.", "portuguese": ["Eu preciso comprar alguns ingredientes.", "Preciso de ingredientes para a receita."]},
    {"english": "Let's bake a cake.", "portuguese": ["Vamos assar um bolo.", "Vamos fazer um bolo."]},
    {"english": "How do you make this sauce?", "portuguese": ["Como você faz esse molho?", "Como é feito esse molho?"]},
    {"english": "I enjoy trying new recipes.", "portuguese": ["Eu gosto de experimentar receitas novas.", "Adoro testar novas receitas."]},
    {"english": "Can you help me in the kitchen?", "portuguese": ["Você pode me ajudar na cozinha?", "Pode me dar uma mão na cozinha?"]},
    {"english": "I need to preheat the oven.", "portuguese": ["Eu preciso pré-aquecer o forno.", "Tenho que ligar o forno antes."]},
    {"english": "This soup needs more seasoning.", "portuguese": ["Essa sopa precisa de mais tempero.", "Falta tempero nessa sopa."]},
    {"english": "Do you have a vegetarian recipe?", "portuguese": ["Você tem uma receita vegetariana?", "Conhece alguma receita vegetariana?"]},
    {"english": "Let's make a salad.", "portuguese": ["Vamos fazer uma salada.", "Vamos preparar uma salada."]},
    {"english": "What is your favorite dish?", "portuguese": ["Qual é o seu prato favorito?", "Qual seu prato preferido?"]},
    {"english": "Can you chop the vegetables?", "portuguese": ["Você pode picar os vegetais?", "Pode cortar os legumes?"]},
    {"english": "The food smells delicious.", "portuguese": ["A comida está com um cheiro delicioso.", "O cheiro da comida está ótimo."]},
    {"english": "I need a larger pot.", "portuguese": ["Eu preciso de uma panela maior.", "Preciso de uma panela grande."]},
    {"english": "Do you want to try some?", "portuguese": ["Você quer experimentar?", "Quer provar um pouco?"]},
    {"english": "This dish is too spicy.", "portuguese": ["Este prato está muito picante.", "Está muito apimentado."]},
    {"english": "I love making desserts.", "portuguese": ["Eu adoro fazer sobremesas.", "Amo preparar doces."]},
    {"english": "What should we cook for dinner?", "portuguese": ["O que devemos cozinhar para o jantar?", "O que vamos fazer para o jantar?"]},
    {"english": "Good morning!", "portuguese": ["Bom dia!", "Bom dia a todos!"]},
    {"english": "Hello, how are you?", "portuguese": ["Olá, como você está?", "Oi, tudo bem?"]},
    {"english": "Nice to meet you.", "portuguese": ["Prazer em conhecê-lo.", "Muito prazer."]},
    {"english": "Good evening, everyone.", "portuguese": ["Boa noite a todos.", "Boa noite, pessoal."]},
    {"english": "Hi there!", "portuguese": ["Oi!", "E aí!"]},
    {"english": "Long time no see!", "portuguese": ["Quanto tempo!", "Há quanto tempo!"]},
    {"english": "How have you been?", "portuguese": ["Como você tem estado?", "Como tem passado?"]},
    {"english": "Welcome!", "portuguese": ["Bem-vindo!", "Seja bem-vindo!"]},
    {"english": "Have a great day!", "portuguese": ["Tenha um ótimo dia!", "Tenha um bom dia!"]},
    {"english": "See you later.", "portuguese": ["Até logo.", "Até mais."]},
    {"english": "Take care.", "portuguese": ["Cuide-se.", "Se cuide."]},
    {"english": "Goodbye!", "portuguese": ["Adeus!", "Tchau!"]},
    {"english": "Happy birthday!", "portuguese": ["Feliz aniversário!", "Parabéns!"]},
    {"english": "Congratulations!", "portuguese": ["Parabéns!", "Meus parabéns!"]},
    {"english": "I'm glad to see you.", "portuguese": ["Estou feliz em te ver.", "Fico contente em te ver."]},
    {"english": "Good night, sleep well.", "portuguese": ["Boa noite, durma bem.", "Boa noite, durma tranquilo."]},
    {"english": "Hello there!", "portuguese": ["Olá!", "Oi, pessoal!"]},
    {"english": "Good afternoon.", "portuguese": ["Boa tarde.", "Boa tarde a todos."]},
    {"english": "How is it going?", "portuguese": ["Como vai?", "Como está indo?"]},
    {"english": "Pleased to meet you.", "portuguese": ["Prazer em conhecê-lo.", "Muito prazer em conhecê-lo."]},
    {"english": "I need to book a flight.", "portuguese": ["Eu preciso reservar um voo.", "Preciso marcar um voo."]},
    {"english": "Where are you traveling to?", "portuguese": ["Para onde você está viajando?", "Para onde vai viajar?"]},
    {"english": "Have a safe trip.", "portuguese": ["Tenha uma viagem segura.", "Boa viagem!"]},
    {"english": "Don't forget your passport.", "portuguese": ["Não esqueça seu passaporte.", "Lembre-se do seu passaporte."]},
    {"english": "Do you have travel insurance?", "portuguese": ["Você tem seguro de viagem?", "Você fez seguro de viagem?"]},
    {"english": "What time is your flight?", "portuguese": ["Que horas é o seu voo?", "Qual é o horário do seu voo?"]},
    {"english": "Can you recommend a good hotel?", "portuguese": ["Você pode recomendar um bom hotel?", "Pode sugerir um hotel bom?"]},
    {"english": "I love exploring new places.", "portuguese": ["Eu adoro explorar novos lugares.", "Amo conhecer novos lugares."]},
    {"english": "What is the best way to get around the city?", "portuguese": ["Qual é a melhor maneira de se locomover pela cidade?", "Como é melhor se locomover na cidade?"]},
    {"english": "Let's go on a road trip!", "portuguese": ["Vamos fazer uma viagem de carro!", "Vamos fazer uma viagem de estrada!"]},
    {"english": "I need to pack my bags.", "portuguese": ["Eu preciso fazer as malas.", "Preciso arrumar minhas malas."]},
    {"english": "What is the local currency?", "portuguese": ["Qual é a moeda local?", "Que moeda se usa aqui?"]},
    {"english": "How much is the fare?", "portuguese": ["Quanto custa a passagem?", "Qual é o preço da passagem?"]},
    {"english": "I enjoy visiting museums.", "portuguese": ["Eu gosto de visitar museus.", "Adoro ir a museus."]},
    {"english": "Do you have a travel guide?", "portuguese": ["Você tem um guia de viagem?", "Tem algum guia de turismo?"]},
    {"english": "What are the tourist attractions?", "portuguese": ["Quais são as atrações turísticas?", "Quais pontos turísticos devo visitar?"]},
    {"english": "Can you speak English?", "portuguese": ["Você fala inglês?", "Você sabe falar inglês?"]},
    {"english": "Where is the nearest ATM?", "portuguese": ["Onde fica o caixa eletrônico mais próximo?", "Onde está o banco mais perto?"]},
    {"english": "I need a map of the city.", "portuguese": ["Eu preciso de um mapa da cidade.", "Pode me dar um mapa da cidade?"]},
    {"english": "Is it safe to travel alone?", "portuguese": ["É seguro viajar sozinho?", "Viajar sozinho é seguro?"]},
    {"english": "Let's go for a walk in the park.", "portuguese": ["Vamos dar uma volta no parque.", "Vamos passear no parque."]},
    {"english": "I love visiting museums.", "portuguese": ["Eu adoro visitar museus.", "Gosto muito de ir a museus."]},
    {"english": "Can we go to the beach today?", "portuguese": ["Podemos ir à praia hoje?", "Vamos à praia hoje?"]},
    {"english": "There is a nice restaurant downtown.", "portuguese": ["Há um restaurante legal no centro.", "Tem um bom restaurante no centro da cidade."]},
    {"english": "We should visit the zoo.", "portuguese": ["Devemos visitar o zoológico.", "Vamos ao zoológico."]},
    {"english": "How about a trip to the countryside?", "portuguese": ["Que tal uma viagem ao campo?", "Vamos fazer uma viagem ao interior?"]},
    {"english": "I enjoy hiking in the mountains.", "portuguese": ["Eu gosto de fazer trilhas nas montanhas.", "Adoro caminhar nas montanhas."]},
    {"english": "Let's explore the city together.", "portuguese": ["Vamos explorar a cidade juntos.", "Vamos conhecer a cidade juntos."]},
    {"english": "The botanical garden is beautiful.", "portuguese": ["O jardim botânico é lindo.", "O jardim botânico é maravilhoso."]},
    {"english": "We can go cycling by the river.", "portuguese": ["Podemos andar de bicicleta à beira do rio.", "Vamos pedalar pelo rio?"]},
    {"english": "I want to see the sunset from the hill.", "portuguese": ["Eu quero ver o pôr do sol do morro.", "Quero assistir ao pôr do sol do alto da colina."]},
    {"english": "The amusement park has great rides.", "portuguese": ["O parque de diversões tem ótimos brinquedos.", "O parque de diversões é muito divertido."]},
    {"english": "We could go fishing this weekend.", "portuguese": ["Podemos pescar neste fim de semana.", "Vamos pescar no fim de semana?"]},
    {"english": "Let's have a picnic in the park.", "portuguese": ["Vamos fazer um piquenique no parque.", "Vamos fazer um lanche no parque."]},
    {"english": "I enjoy walking through the city streets.", "portuguese": ["Eu gosto de andar pelas ruas da cidade.", "Gosto de caminhar pelas ruas da cidade."]},
    {"english": "The view from the bridge is amazing.", "portuguese": ["A vista da ponte é incrível.", "A vista da ponte é maravilhosa."]},
    {"english": "There is a great art gallery nearby.", "portuguese": ["Há uma ótima galeria de arte aqui perto.", "Tem uma galeria de arte muito boa por aqui."]},
    {"english": "Let's go to the concert tonight.", "portuguese": ["Vamos ao show esta noite.", "Vamos ao concerto hoje à noite."]},
    {"english": "The local market is worth a visit.", "portuguese": ["O mercado local vale a visita.", "O mercado local é muito interessante."]},
    {"english": "Can we visit the aquarium tomorrow?", "portuguese": ["Podemos visitar o aquário amanhã?", "Vamos ao aquário amanhã?"]},
    {"english": "I need to buy some groceries.", "portuguese": ["Eu preciso comprar alguns mantimentos.", "Preciso fazer compras."]},
    {"english": "Do we have enough milk?", "portuguese": ["Temos leite suficiente?", "Ainda temos leite?"]},
    {"english": "Where is the bread aisle?", "portuguese": ["Onde fica a seção de pães?", "Onde está a seção de pães?"]},
    {"english": "I forgot to buy eggs.", "portuguese": ["Eu esqueci de comprar ovos.", "Esqueci de pegar os ovos."]},
    {"english": "Can you get some fruits?", "portuguese": ["Você pode pegar algumas frutas?", "Pode pegar umas frutas?"]},
    {"english": "The prices are really high today.", "portuguese": ["Os preços estão muito altos hoje.", "Os preços estão caros hoje."]},
    {"english": "Let's check the offers.", "portuguese": ["Vamos verificar as ofertas.", "Vamos ver as promoções."]},
    {"english": "I need a shopping cart.", "portuguese": ["Eu preciso de um carrinho de compras.", "Preciso de um carrinho."]},
    {"english": "Do you have a shopping list?", "portuguese": ["Você tem uma lista de compras?", "Fez uma lista de compras?"]},
    {"english": "Where can I find the vegetables?", "portuguese": ["Onde posso encontrar os vegetais?", "Onde ficam os legumes?"]},
    {"english": "We need more coffee.", "portuguese": ["Precisamos de mais café.", "Estamos precisando de café."]},
    {"english": "Are there any discounts?", "portuguese": ["Tem algum desconto?", "Há promoções?"]},
    {"english": "I can't find the sugar.", "portuguese": ["Não consigo encontrar o açúcar.", "Não acho o açúcar."]},
    {"english": "The store is crowded.", "portuguese": ["A loja está lotada.", "O mercado está cheio."]},
    {"english": "Let's go to the checkout.", "portuguese": ["Vamos ao caixa.", "Vamos pagar."]},
    {"english": "Did you bring your reusable bags?", "portuguese": ["Você trouxe suas sacolas reutilizáveis?", "Trouxe suas ecobags?"]},
    {"english": "I need to buy some cleaning products.", "portuguese": ["Eu preciso comprar alguns produtos de limpeza.", "Preciso pegar produtos de limpeza."]},
    {"english": "Where is the dairy section?", "portuguese": ["Onde fica a seção de laticínios?", "Onde estão os produtos lácteos?"]},
    {"english": "The market closes at 8 PM.", "portuguese": ["O mercado fecha às 20h.", "O supermercado fecha às 8 da noite."]},
    {"english": "I love fresh produce.", "portuguese": ["Eu adoro produtos frescos.", "Amo frutas e verduras frescas."]},
    {"english": "What time does the flight depart?", "portuguese": ["A que horas o voo parte?", "Que horas sai o voo?"]},
    {"english": "Please, fasten your seatbelt.", "portuguese": ["Por favor, afivele seu cinto de segurança.", "Por favor, aperte o cinto."]},
    {"english": "Can I have a window seat?", "portuguese": ["Posso ter um assento na janela?", "Posso sentar na janela?"]},
    {"english": "The plane is ready for takeoff.", "portuguese": ["O avião está pronto para decolar.", "O avião está pronto para a decolagem."]},
    {"english": "What is the gate number?", "portuguese": ["Qual é o número do portão?", "Qual o portão de embarque?"]},
    {"english": "I need to check my baggage.", "portuguese": ["Preciso despachar minha bagagem.", "Tenho que despachar a mala."]},
    {"english": "Can you bring me a blanket?", "portuguese": ["Você pode me trazer um cobertor?", "Pode trazer um cobertor, por favor?"]},
    {"english": "How long is the flight?", "portuguese": ["Qual a duração do voo?", "Quanto tempo dura o voo?"]},
    {"english": "The flight is delayed.", "portuguese": ["O voo está atrasado.", "Houve um atraso no voo."]},
    {"english": "Is there Wi-Fi on the plane?", "portuguese": ["Tem Wi-Fi no avião?", "O avião tem Wi-Fi?"]},
    {"english": "Where is the nearest emergency exit?", "portuguese": ["Onde fica a saída de emergência mais próxima?", "Onde está a saída de emergência?"]},
    {"english": "Can I have some water, please?", "portuguese": ["Posso ter um pouco de água, por favor?", "Pode me trazer água, por favor?"]},
    {"english": "What time do we land?", "portuguese": ["A que horas vamos aterrissar?", "Que horas chegamos ao destino?"]},
    {"english": "Please turn off your electronic devices.", "portuguese": ["Por favor, desligue seus dispositivos eletrônicos.", "Desliguem os aparelhos eletrônicos, por favor."]},
    {"english": "Do you have any vegetarian meals?", "portuguese": ["Você tem refeições vegetarianas?", "Há opções de refeições vegetarianas?"]},
    {"english": "How much luggage can I carry?", "portuguese": ["Quanto de bagagem posso levar?", "Qual o limite de bagagem?"]},
    {"english": "Can I change my seat?", "portuguese": ["Posso mudar de assento?", "É possível trocar de assento?"]},
    {"english": "The turbulence was quite strong.", "portuguese": ["A turbulência foi bem forte.", "Houve muita turbulência."]},
    {"english": "Where is the flight information display?", "portuguese": ["Onde está o painel de informações de voo?", "Onde vejo as informações do voo?"]},
    {"english": "Can I have a pillow, please?", "portuguese": ["Posso ter um travesseiro, por favor?", "Pode me trazer um travesseiro, por favor?"]},
    {"english": "Can I see the menu, please?", "portuguese": ["Posso ver o cardápio, por favor?", "Pode me mostrar o menu, por favor?"]},
    {"english": "What do you recommend?", "portuguese": ["O que você recomenda?", "Qual a sugestão da casa?"]},
    {"english": "I'll have the steak.", "portuguese": ["Eu vou querer o bife.", "Vou pedir o bife."]},
    {"english": "Can I get this to go?", "portuguese": ["Pode embalar para viagem?", "Posso levar isso para casa?"]},
    {"english": "Do you have vegetarian options?", "portuguese": ["Vocês têm opções vegetarianas?", "Há pratos vegetarianos?"]},
    {"english": "I'd like a table for two.", "portuguese": ["Gostaria de uma mesa para dois.", "Uma mesa para duas pessoas, por favor."]},
    {"english": "Can I have some water, please?", "portuguese": ["Pode me trazer água, por favor?", "Posso pedir um pouco de água?"]},
    {"english": "What are today's specials?", "portuguese": ["Quais são os pratos do dia?", "Qual é o especial de hoje?"]},
    {"english": "Could you bring the bill, please?", "portuguese": ["Pode trazer a conta, por favor?", "A conta, por favor."]},
    {"english": "I'd like to make a reservation.", "portuguese": ["Gostaria de fazer uma reserva.", "Quero reservar uma mesa."]},
    {"english": "Excuse me, where is the restroom?", "portuguese": ["Com licença, onde fica o banheiro?", "Onde é o toalete?"]},
    {"english": "Can I have the dessert menu?", "portuguese": ["Posso ver o cardápio de sobremesas?", "Pode trazer o menu de sobremesas?"]},
    {"english": "Is there a children's menu?", "portuguese": ["Tem um cardápio infantil?", "Vocês têm opções para crianças?"]},
    {"english": "Can I get a refill?", "portuguese": ["Posso pedir uma reposição?", "Pode encher meu copo novamente?"]},
    {"english": "I have a food allergy.", "portuguese": ["Tenho alergia alimentar.", "Sou alérgico a alguns alimentos."]},
    {"english": "How spicy is this dish?", "portuguese": ["Quão picante é esse prato?", "Esse prato é muito apimentado?"]},
    {"english": "Can I have this without onions?", "portuguese": ["Posso pedir isso sem cebola?", "Pode fazer esse prato sem cebola?"]},
    {"english": "Do you accept credit cards?", "portuguese": ["Vocês aceitam cartão de crédito?", "Aceitam pagamento com cartão?"]},
    {"english": "What time do you close?", "portuguese": ["A que horas vocês fecham?", "Qual é o horário de fechamento?"]},
    {"english": "The food was delicious.", "portuguese": ["A comida estava deliciosa.", "A refeição foi excelente."]},
    {"english": "Do you play any sports?", "portuguese": ["Você pratica algum esporte?", "Você joga algum esporte?"]},
    {"english": "I love playing soccer.", "portuguese": ["Eu adoro jogar futebol.", "Amo jogar bola."]},
    {"english": "What is your favorite team?", "portuguese": ["Qual é o seu time favorito?", "Qual o seu time do coração?"]},
    {"english": "Let's go for a run.", "portuguese": ["Vamos correr.", "Vamos fazer uma corrida."]},
    {"english": "Do you like basketball?", "portuguese": ["Você gosta de basquete?", "Você curte basquete?"]},
    {"english": "Can you swim?", "portuguese": ["Você sabe nadar?", "Você nada?"]},
    {"english": "I enjoy watching tennis.", "portuguese": ["Eu gosto de assistir tênis.", "Adoro ver partidas de tênis."]},
    {"english": "What is the score?", "portuguese": ["Qual é o placar?", "Quanto está o jogo?"]},
    {"english": "Do you want to join our team?", "portuguese": ["Quer se juntar ao nosso time?", "Quer fazer parte do nosso time?"]},
    {"english": "Where is the nearest gym?", "portuguese": ["Onde fica a academia mais próxima?", "Onde é a academia mais perto?"]},
    {"english": "I need to exercise more.", "portuguese": ["Eu preciso me exercitar mais.", "Preciso fazer mais exercícios."]},
    {"english": "Do you follow the Olympics?", "portuguese": ["Você acompanha as Olimpíadas?", "Você assiste às Olimpíadas?"]},
    {"english": "I am a big fan of volleyball.", "portuguese": ["Sou um grande fã de vôlei.", "Adoro vôlei."]},
    {"english": "Let's play some table tennis.", "portuguese": ["Vamos jogar tênis de mesa.", "Vamos jogar pingue-pongue."]},
    {"english": "She practices yoga every day.", "portuguese": ["Ela pratica ioga todos os dias.", "Ela faz ioga diariamente."]},
    {"english": "I need to buy new running shoes.", "portuguese": ["Eu preciso comprar tênis novos para correr.", "Preciso de tênis de corrida novos."]},
    {"english": "Are you interested in martial arts?", "portuguese": ["Você se interessa por artes marciais?", "Gosta de artes marciais?"]},
    {"english": "He is a skilled gymnast.", "portuguese": ["Ele é um ginasta habilidoso.", "Ele é muito bom na ginástica."]},
    {"english": "The stadium is packed.", "portuguese": ["O estádio está lotado.", "O estádio está cheio."]},
    {"english": "I played tennis yesterday.", "portuguese": ["Eu joguei tênis ontem.", "Ontem joguei tênis."]},
    {"english": "Do you have the latest software update?", "portuguese": ["Você tem a última atualização de software?", "Você já atualizou o software?"]},
    {"english": "My computer is running slow.", "portuguese": ["Meu computador está lento.", "Meu PC está devagar."]},
    {"english": "Can you help me fix this bug?", "portuguese": ["Você pode me ajudar a corrigir esse bug?", "Pode me ajudar a resolver esse problema?"]},
    {"english": "I need to back up my data.", "portuguese": ["Eu preciso fazer backup dos meus dados.", "Preciso salvar uma cópia dos meus arquivos."]},
    {"english": "Do you have a good antivirus?", "portuguese": ["Você tem um bom antivírus?", "Qual antivírus você usa?"]},
    {"english": "The internet connection is unstable.", "portuguese": ["A conexão com a internet está instável.", "A internet está caindo."]},
    {"english": "What is your Wi-Fi password?", "portuguese": ["Qual é a senha do Wi-Fi?", "Pode me dar a senha do Wi-Fi?"]},
    {"english": "I need to install a new printer.", "portuguese": ["Eu preciso instalar uma nova impressora.", "Preciso configurar uma nova impressora."]},
    {"english": "Can you share this file with me?", "portuguese": ["Você pode compartilhar esse arquivo comigo?", "Pode me enviar esse arquivo?"]},
    {"english": "I forgot my password.", "portuguese": ["Eu esqueci minha senha.", "Não lembro a minha senha."]},
    {"english": "Let's schedule a video conference.", "portuguese": ["Vamos agendar uma videoconferência.", "Vamos marcar uma chamada de vídeo."]},
    {"english": "The system crashed.", "portuguese": ["O sistema travou.", "O sistema caiu."]},
    {"english": "Do you use cloud storage?", "portuguese": ["Você usa armazenamento em nuvem?", "Você guarda arquivos na nuvem?"]},
    {"english": "I need to update my drivers.", "portuguese": ["Eu preciso atualizar meus drivers.", "Preciso atualizar os drivers do meu computador."]},
    {"english": "This app is very useful.", "portuguese": ["Este aplicativo é muito útil.", "Esse app é ótimo."]},
    {"english": "I am learning to code.", "portuguese": ["Eu estou aprendendo a programar.", "Estou estudando programação."]},
    {"english": "Can you connect to the server?", "portuguese": ["Você consegue se conectar ao servidor?", "Pode acessar o servidor?"]},
    {"english": "My phone battery drains quickly.", "portuguese": ["A bateria do meu telefone acaba rápido.", "A bateria do meu celular descarrega muito rápido."]},
    {"english": "Do you have a tech support contact?", "portuguese": ["Você tem um contato de suporte técnico?", "Você sabe quem pode ajudar com suporte técnico?"]},
    {"english": "I need to reboot my system.", "portuguese": ["Eu preciso reiniciar meu sistema.", "Preciso reiniciar o computador."]},
    {"english": "I have a doctor's appointment today.", "portuguese": ["Tenho uma consulta médica hoje.", "Tenho um horário no médico hoje."]},
    {"english": "How are you feeling?", "portuguese": ["Como você está se sentindo?", "Você está bem?"]},
    {"english": "I need to take my medication.", "portuguese": ["Eu preciso tomar meu remédio.", "Preciso tomar meu medicamento."]},
    {"english": "You should get some rest.", "portuguese": ["Você deveria descansar um pouco.", "Descanse um pouco."]},
    {"english": "Are you allergic to anything?", "portuguese": ["Você é alérgico a alguma coisa?", "Tem alguma alergia?"]},
    {"english": "I need to schedule a check-up.", "portuguese": ["Eu preciso agendar um check-up.", "Preciso marcar um check-up."]},
    {"english": "Drink plenty of water.", "portuguese": ["Beba bastante água.", "Hidrate-se bem."]},
    {"english": "I feel much better now.", "portuguese": ["Eu me sinto muito melhor agora.", "Estou bem melhor agora."]},
    {"english": "Please call an ambulance.", "portuguese": ["Por favor, chame uma ambulância.", "Ligue para a ambulância, por favor."]},
    {"english": "I have a headache.", "portuguese": ["Estou com dor de cabeça.", "Tenho uma dor de cabeça."]},
    {"english": "How long have you been feeling sick?", "portuguese": ["Há quanto tempo você está se sentindo mal?", "Quanto tempo você está doente?"]},
    {"english": "Take this medicine twice a day.", "portuguese": ["Tome este remédio duas vezes ao dia.", "Tome este medicamento duas vezes por dia."]},
    {"english": "I need to see a specialist.", "portuguese": ["Eu preciso ver um especialista.", "Preciso consultar um especialista."]},
    {"english": "You have a fever.", "portuguese": ["Você está com febre.", "Você está febril."]},
    {"english": "I need to get vaccinated.", "portuguese": ["Eu preciso me vacinar.", "Preciso tomar a vacina."]},
    {"english": "How is your health?", "portuguese": ["Como está sua saúde?", "Sua saúde está bem?"]},
    {"english": "I have a stomachache.", "portuguese": ["Estou com dor de estômago.", "Tenho uma dor no estômago."]},
    {"english": "You should see a doctor.", "portuguese": ["Você deveria consultar um médico.", "Procure um médico."]},
    {"english": "I am feeling dizzy.", "portuguese": ["Estou me sentindo tonto.", "Estou com tontura."]},
    {"english": "Take deep breaths.", "portuguese": ["Respire fundo.", "Faça respirações profundas."]},
    {"english": "I need to study for my exams.", "portuguese": ["Eu preciso estudar para os meus exames.", "Preciso me preparar para as provas."]},
    {"english": "What is your favorite subject?", "portuguese": ["Qual é a sua matéria favorita?", "Qual a disciplina que você mais gosta?"]},
    {"english": "The library is very quiet.", "portuguese": ["A biblioteca é muito tranquila.", "A biblioteca é bem silenciosa."]},
    {"english": "Do you have any homework?", "portuguese": ["Você tem algum dever de casa?", "Tem tarefa para fazer?"]},
    {"english": "I enjoy learning new things.", "portuguese": ["Eu gosto de aprender coisas novas.", "Adoro descobrir coisas novas."]},
    {"english": "Can you help me with this assignment?", "portuguese": ["Você pode me ajudar com esta tarefa?", "Pode me ajudar com esse trabalho?"]},
    {"english": "The teacher is very knowledgeable.", "portuguese": ["O professor é muito conhecedor.", "A professora tem muito conhecimento."]},
    {"english": "I have a test tomorrow.", "portuguese": ["Eu tenho uma prova amanhã.", "Tenho um exame amanhã."]},
    {"english": "We need to work on our project.", "portuguese": ["Nós precisamos trabalhar no nosso projeto.", "Precisamos avançar no nosso trabalho."]},
    {"english": "The classroom is spacious.", "portuguese": ["A sala de aula é espaçosa.", "A sala de aula é grande."]},
    {"english": "I am taking an online course.", "portuguese": ["Eu estou fazendo um curso online.", "Estou matriculado em um curso virtual."]},
    {"english": "Do you like math?", "portuguese": ["Você gosta de matemática?", "Você curte matemática?"]},
    {"english": "I need to improve my grades.", "portuguese": ["Eu preciso melhorar minhas notas.", "Tenho que melhorar meu desempenho."]},
    {"english": "We have a group study session.", "portuguese": ["Nós temos uma sessão de estudo em grupo.", "Vamos estudar em grupo."]},
    {"english": "The lecture was very informative.", "portuguese": ["A palestra foi muito informativa.", "A aula foi bem esclarecedora."]},
    {"english": "Can I borrow your notes?", "portuguese": ["Posso pegar suas anotações emprestadas?", "Você me empresta suas notas?"]},
    {"english": "I have a lot of assignments this week.", "portuguese": ["Eu tenho muitas tarefas esta semana.", "Tenho muitos trabalhos para fazer esta semana."]},
    {"english": "What time is the next class?", "portuguese": ["Que horas é a próxima aula?", "Qual o horário da próxima aula?"]},
    {"english": "The school has a great science lab.", "portuguese": ["A escola tem um ótimo laboratório de ciências.", "O laboratório de ciências da escola é muito bom."]},
    {"english": "I need to register for my classes.", "portuguese": ["Eu preciso me registrar para as minhas aulas.", "Preciso me matricular nas aulas."]}
]