[
    {"english": "be", "portuguese": ["ser", "estar"]},
    {"english": "have", "portuguese": ["ter"]},
    {"english": "do", "portuguese": ["fazer"]},
    {"english": "say", "portuguese": ["dizer"]},
    {"english": "go", "portuguese": ["ir"]},
    {"english": "get", "portuguese": ["obter", "conseguir"]},
    {"english": "make", "portuguese": ["fazer", "criar"]},
    {"english": "know", "portuguese": ["saber", "conhecer"]},
    {"english": "think", "portuguese": ["pensar"]},
    {"english": "take", "portuguese": ["pegar", "tomar", "levar"]},
    {"english": "see", "portuguese": ["ver"]},
    {"english": "come", "portuguese": ["vir"]},
    {"english": "want", "portuguese": ["querer"]},
    {"english": "use", "portuguese": ["usar"]},
    {"english": "find", "portuguese": ["encontrar", "descobrir", "localizar"]},
    {"english": "give", "portuguese": ["dar"]},
    {"english": "tell", "portuguese": ["contar"]},
    {"english": "work", "portuguese": ["trabalhar", "trabalho", "serviço", "tarefa"]},
    {"english": "call", "portuguese": ["chamar", "ligar"]},
    {"english": "try", "portuguese": ["tentar"]},
    {"english": "ask", "portuguese": ["perguntar"]},
    {"english": "need", "portuguese": ["precisar"]},
    {"english": "feel", "portuguese": ["sentir"]},
    {"english": "leave", "portuguese": ["deixar", "sair"]},
    {"english": "put", "portuguese": ["colocar"]},
    {"english": "mean", "portuguese": ["significar"]},
    {"english": "keep", "portuguese": ["manter"]},
    {"english": "let", "portuguese": ["deixar"]},
    {"english": "help", "portuguese": ["ajudar"]},
    {"english": "talk", "portuguese": ["conversar"]},
    {"english": "turn", "portuguese": ["virar"]},
    {"english": "start", "portuguese": ["começar", "iniciar", "ligar"]},
    {"english": "show", "portuguese": ["mostrar"]},
    {"english": "hear", "portuguese": ["ouvir"]},
    {"english": "play", "portuguese": ["jogar", "brincar"]},
    {"english": "run", "portuguese": ["correr"]},
    {"english": "move", "portuguese": ["mover"]},
    {"english": "like", "portuguese": ["gostar"]},
    {"english": "live", "portuguese": ["viver", "vivo"]},
    {"english": "believe", "portuguese": ["acreditar"]},
    {"english": "hold", "portuguese": ["segurar"]},
    {"english": "bring", "portuguese": ["trazer"]},
    {"english": "write", "portuguese": ["escrever"]},
    {"english": "sit", "portuguese": ["sentar"]},
    {"english": "stand", "portuguese": ["ficar de pé"]},
    {"english": "lose", "portuguese": ["perder"]},
    {"english": "pay", "portuguese": ["pagar"]},
    {"english": "meet", "portuguese": ["encontrar", "reunir", "conhecer"]},
    {"english": "include", "portuguese": ["incluir"]},
    {"english": "set", "portuguese": ["definir"]},
    {"english": "learn", "portuguese": ["aprender"]},
    {"english": "achieve", "portuguese": ["alcançar"]},
    {"english": "challenge", "portuguese": ["desafio"]},
    {"english": "creative", "portuguese": ["criativo"]},
    {"english": "efficient", "portuguese": ["eficiente"]},
    {"english": "focus", "portuguese": ["foco", "focar"]},
    {"english": "improve", "portuguese": ["melhorar", "aprimorar", "aperfeiçoar"]},
    {"english": "knowledge", "portuguese": ["conhecimento"]},
    {"english": "motivate", "portuguese": ["motivar"]},
    {"english": "opportunity", "portuguese": ["oportunidade"]},
    {"english": "success", "portuguese": ["sucesso"]},
    {"english": "adapt", "portuguese": ["adaptar"]},
    {"english": "collaboration", "portuguese": ["colaboração"]},
    {"english": "effective", "portuguese": ["eficaz", "efetivo"]},
    {"english": "passion", "portuguese": ["paixão"]},
    {"english": "resourceful", "portuguese": ["engenhoso"]},
    {"english": "innovate", "portuguese": ["inovar"]},
    {"english": "perseverance", "portuguese": ["perseverança"]},
    {"english": "resilience", "portuguese": ["resiliência"]},
    {"english": "vision", "portuguese": ["visão"]},
    {"english": "wisdom", "portuguese": ["sabedoria"]},
    {"english": "walk", "portuguese": ["andar"]},
    {"english": "smile", "portuguese": ["sorrir"]},
    {"english": "jump", "portuguese": ["pular"]},
    {"english": "sing", "portuguese": ["cantar"]},
    {"english": "dance", "portuguese": ["dançar"]},
    {"english": "cook", "portuguese": ["cozinhar"]},
    {"english": "watch", "portuguese": ["assistir"]},
    {"english": "travel", "portuguese": ["viajar"]},
    {"english": "paint", "portuguese": ["pintar"]},
    {"english": "buy", "portuguese": ["comprar"]},
    {"english": "sell", "portuguese": ["vender"]},
    {"english": "finish", "portuguese": ["terminar"]},
    {"english": "share", "portuguese": ["compartilhar"]},
    {"english": "fix", "portuguese": ["consertar"]},
    {"english": "break", "portuguese": ["quebrar"]},
    {"english": "climb", "portuguese": ["escalar"]},
    {"english": "enjoy", "portuguese": ["aproveitar", "gostar", "desfrutar", "curtir"]},
    {"english": "build", "portuguese": ["construir"]},
    {"english": "clean", "portuguese": ["limpar"]},
    {"english": "draw", "portuguese": ["desenhar"]},
    {"english": "study", "portuguese": ["estudar"]},
    {"english": "open", "portuguese": ["abrir"]},
    {"english": "close", "portuguese": ["fechar"]},
    {"english": "push", "portuguese": ["empurrar"]},
    {"english": "pull", "portuguese": ["puxar"]},
    {"english": "wait", "portuguese": ["esperar", "aguardar"]},
    {"english": "change", "portuguese": ["mudar"]},
    {"english": "listen", "portuguese": ["escutar"]},
    {"english": "drive", "portuguese": ["dirigir"]},
    {"english": "Although", "portuguese": ["embora", "apesar de"]},
    {"english": "Because", "portuguese": ["porque"]},
    {"english": "Therefore", "portuguese": ["portanto", "por isso"]},
    {"english": "However", "portuguese": ["no entanto", "porém"]},
    {"english": "Moreover", "portuguese": ["além disso"]},
    {"english": "Instead", "portuguese": ["em vez disso"]},
    {"english": "Meanwhile", "portuguese": ["enquanto isso"]},
    {"english": "Since", "portuguese": ["desde que", "já que"]},
    {"english": "In addition", "portuguese": ["além disso"]},
    {"english": "Unless", "portuguese": ["a menos que"]},
    {"english": "Brave", "portuguese": ["corajoso"]},
    {"english": "Curious", "portuguese": ["curioso"]},
    {"english": "Elevate", "portuguese": ["elevar"]},
    {"english": "Freedom", "portuguese": ["liberdade"]},
    {"english": "Grateful", "portuguese": ["grato"]},
    {"english": "Harmony", "portuguese": ["harmonia"]},
    {"english": "Inspire", "portuguese": ["inspirar"]},
    {"english": "Journey", "portuguese": ["jornada"]},
    {"english": "Kindness", "portuguese": ["bondade"]},
    {"english": "Laughter", "portuguese": ["riso"]},
    {"english": "Marvel", "portuguese": ["maravilha"]},
    {"english": "Optimism", "portuguese": ["otimismo"]},
    {"english": "Peace", "portuguese": ["paz"]},
    {"english": "Quest", "portuguese": ["busca", "procura"]},
    {"english": "Radiant", "portuguese": ["radiante"]},
    {"english": "Serene", "portuguese": ["sereno"]},
    {"english": "Thrive", "portuguese": ["prosperar"]},
    {"english": "Unique", "portuguese": ["único"]},
    {"english": "Victory", "portuguese": ["vitória"]},
    {"english": "Zeal", "portuguese": ["zelo"]},
    {"english": "happiness", "portuguese": ["felicidade"]},
    {"english": "Compassion", "portuguese": ["compaixão"]},
    {"english": "Devote", "portuguese": ["devotar"]},
    {"english": "Empathy", "portuguese": ["empatia"]},
    {"english": "Flourish", "portuguese": ["florescer"]},
    {"english": "Gracious", "portuguese": ["gracioso"]},
    {"english": "Hope", "portuguese": ["esperança"]},
    {"english": "Integrity", "portuguese": ["integridade"]},
    {"english": "Joy", "portuguese": ["alegria"]},
    {"english": "Love", "portuguese": ["amor"]},
    {"english": "Persevere", "portuguese": ["perseverar"]},
    {"english": "analyze", "portuguese": ["analisar", "analise"]},
    {"english": "connect", "portuguese": ["conectar"]},
    {"english": "explore", "portuguese": ["explorar"]},
    {"english": "reflect", "portuguese": ["refletir"]},
    {"english": "achievable", "portuguese": ["alcançável", "realizável", "realizável"]},
    {"english": "curiosity", "portuguese": ["curiosidade"]},
    {"english": "courage", "portuguese": ["coragem"]},
    {"english": "dedicate", "portuguese": ["dedicar"]},
    {"english": "cancel", "portuguese": ["cancelar"]},
    {"english": "combine", "portuguese": ["combinar"]},
    {"english": "complete", "portuguese": ["completar", "completo", "completa"]},
    {"english": "consider", "portuguese": ["considerar"]},
    {"english": "continue", "portuguese": ["continuar"]},
    {"english": "control", "portuguese": ["controlar", "controle"]},
    {"english": "define", "portuguese": ["definir"]},
    {"english": "explain", "portuguese": ["explicar"]},
    {"english": "ignore", "portuguese": ["ignorar"]},
    {"english": "imagine", "portuguese": ["imaginar"]},
    {"english": "import", "portuguese": ["importar"]},
    {"english": "invite", "portuguese": ["convidar", "convite"]},
    {"english": "limit", "portuguese": ["limitar", "limite"]},
    {"english": "organize", "portuguese": ["organizar"]},
    {"english": "prepare", "portuguese": ["preparar"]},
    {"english": "receive", "portuguese": ["receber"]},
    {"english": "support", "portuguese": ["suportar", "apoiar"]},
    
    
    {"english": "time", "portuguese": ["tempo"]},
    {"english": "people", "portuguese": ["pessoas"]},
    {"english": "way", "portuguese": ["modo", "maneira", "forma"]},
    {"english": "water", "portuguese": ["água"]},
    {"english": "man", "portuguese": ["homem"]},
    {"english": "word", "portuguese": ["palavra"]},
    {"english": "part", "portuguese": ["parte"]},
    {"english": "place", "portuguese": ["lugar"]},
    {"english": "things", "portuguese": ["coisas"]},
    {"english": "number", "portuguese": ["número"]},
    {"english": "men", "portuguese": ["homens"]},
    {"english": "name", "portuguese": ["nome"]},
    {"english": "mister", "portuguese": ["senhor"]},
    {"english": "home", "portuguese": ["casa"]},
    {"english": "air", "portuguese": ["ar"]},
    {"english": "line", "portuguese": ["linha", "fila"]},
    {"english": "end", "portuguese": ["final", "fim"]},
    {"english": "sound", "portuguese": ["som"]},
    {"english": "house", "portuguese": ["casa"]},
    {"english": "world", "portuguese": ["mundo"]},
    {"english": "school", "portuguese": ["escola"]},
    {"english": "form", "portuguese": ["forma"]},
    {"english": "food", "portuguese": ["comida"]},
    {"english": "children", "portuguese": ["crianças", "filhos"]},
    {"english": "feet", "portuguese": ["pés"]},
    {"english": "land", "portuguese": ["terra"]},
    {"english": "side", "portuguese": ["lado"]},
    {"english": "boy", "portuguese": ["menino"]},
    {"english": "animals", "portuguese": ["animais"]},
    {"english": "life", "portuguese": ["vida"]},
    {"english": "head", "portuguese": ["cabeça"]},
    {"english": "kind", "portuguese": ["tipo", "espécie", "amigável", "gentil"]},
    {"english": "page", "portuguese": ["página"]},
    {"english": "earth", "portuguese": ["terra"]},
    {"english": "hand", "portuguese": ["mão"]},
    {"english": "year", "portuguese": ["ano", "anos"]},
    {"english": "mother", "portuguese": ["mãe"]},
    {"english": "light", "portuguese": ["luz", "claro", "luminosidade", "iluminar", "acender", "iluminação"]},
    {"english": "country", "portuguese": ["país"]},
    {"english": "father", "portuguese": ["pai"]},
    {"english": "picture", "portuguese": ["imagem", "foto"]},
    {"english": "eyes", "portuguese": ["olhos"]},
    {"english": "thought", "portuguese": ["pensamento"]},
    {"english": "night", "portuguese": ["noite"]},
    {"english": "story", "portuguese": ["história"]},
    
    {"english": "long", "portuguese": ["extenso", "longo"]},
    {"english": "little", "portuguese": ["pouco", "pequeno", "pequena"]},
    {"english": "good", "portuguese": ["bom"]},
    {"english": "new", "portuguese": ["novo"]},
    {"english": "same", "portuguese": ["mesmo"]},
    {"english": "right", "portuguese": ["direito", "direita", "certo", "correto"]},
    {"english": "different", "portuguese": ["diferente"]},
    {"english": "old", "portuguese": ["velho", "antigo"]},
    {"english": "great", "portuguese": ["grande", "ótimo"]},
    {"english": "small", "portuguese": ["pequeno"]},
    {"english": "big", "portuguese": ["grande"]},
    {"english": "own", "portuguese": ["próprio"]},
    {"english": "last", "portuguese": ["último", "última"]},
    {"english": "left", "portuguese": ["esquerda"]},
    {"english": "large", "portuguese": ["grande"]},
    {"english": "important", "portuguese": ["importante"]},
    {"english": "enough", "portuguese": ["suficiente"]},
    {"english": "second", "portuguese": ["segunda", "segundo"]},
    {"english": "first", "portuguese": ["primeiro"]},
    {"english": "well", "portuguese": ["bem"]},
    {"english": "next", "portuguese": ["próximo"]},
    {"english": "high", "portuguese": ["alta", "alto", "elevado"]},
    {"english": "following", "portuguese": ["seguinte"]},
    {"english": "used", "portuguese": ["usado"]},
    {"english": "even", "portuguese": ["igual"]},
    
    {"english": "is", "portuguese": ["é"]},
    {"english": "was", "portuguese": ["era", "estava"]},
    {"english": "are", "portuguese": ["são"]},
    {"english": "had", "portuguese": ["tinha"]},
    {"english": "were", "portuguese": ["foram"]},
    {"english": "can", "portuguese": ["pode"]},
    {"english": "said", "portuguese": ["disse"]},
    {"english": "will", "portuguese": ["vou", "vai", "iremos", "irão"]},
    {"english": "would", "portuguese": ["iria", "poderia", "seria", "teria", "fosse"]},
    {"english": "has", "portuguese": ["tem"]},
    {"english": "could", "portuguese": ["poderia"]},
    {"english": "been", "portuguese": ["sido", "estado"]},
    {"english": "did", "portuguese": ["fez"]},
    {"english": "look", "portuguese": ["olhar", "ver"]},
    {"english": "came", "portuguese": ["veio", "vieram", "chegou"]},
    {"english": "must", "portuguese": ["deve"]},
    {"english": "does", "portuguese": ["faz"]},
    {"english": "went", "portuguese": ["foi", "fui"]},
    {"english": "should", "portuguese": ["deveria"]},
    {"english": "read", "portuguese": ["ler"]},
    {"english": "might", "portuguese": ["poderia"]},
    {"english": "saw", "portuguese": ["viu"]},
    {"english": "asked", "portuguese": ["perguntou"]},
    {"english": "don’t", "portuguese": ["não faça", "não"]},
    {"english": "going", "portuguese": ["indo"]},
    {"english": "took", "portuguese": ["levou"]},
    {"english": "began", "portuguese": ["começou"]},
    {"english": "got", "portuguese": ["obteve"]},
    {"english": "being", "portuguese": ["sendo"]},
    {"english": "made", "portuguese": ["feito"]},
    {"english": "may", "portuguese": ["pode"]},
    {"english": "found", "portuguese": ["encontrado"]},
    {"english": "looked", "portuguese": ["olhou"]},
    {"english": "called", "portuguese": ["chamou", "chamado"]},
    
    {"english": "you", "portuguese": ["você"]},
    {"english": "it", "portuguese": ["ele", "ela"]},
    {"english": "he", "portuguese": ["ele"]},
    {"english": "they", "portuguese": ["eles"]},
    {"english": "this", "portuguese": ["isto"]},
    {"english": "I", "portuguese": ["eu"]},
    {"english": "what", "portuguese": ["o que", "que"]},
    {"english": "all", "portuguese": ["todos", "tudo"]},
    {"english": "we", "portuguese": ["nós"]},
    {"english": "which", "portuguese": ["que"]},
    {"english": "each", "portuguese": ["cada"]},
    {"english": "them", "portuguese": ["eles"]},
    {"english": "she", "portuguese": ["ela"]},
    {"english": "some", "portuguese": ["alguns"]},
    {"english": "these", "portuguese": ["esses"]},
    {"english": "who", "portuguese": ["quem"]},
    {"english": "me", "portuguese": ["me", "mim"]},
    {"english": "another", "portuguese": ["outro"]},
    {"english": "us", "portuguese": ["nos", "nós"]},
    {"english": "something", "portuguese": ["algo", "alguma coisa"]},
    {"english": "both", "portuguese": ["ambos"]},
    {"english": "those", "portuguese": ["aqueles"]},
    
    {"english": "the", "portuguese": ["o", "a", "os", "as"]},
    {"english": "a", "portuguese": ["um"]},
    {"english": "that", "portuguese": ["aquele, isso", "aquilo", "que"]},
    {"english": "his", "portuguese": ["dele"]},
    {"english": "this", "portuguese": ["este", "isto"]},
    {"english": "an ", "portuguese": ["um", "uma", "e"]},
    {"english": "your", "portuguese": ["seu", "sua"]},
    {"english": "their", "portuguese": ["deles", "delas"]},
    {"english": "other", "portuguese": ["outros"]},
    {"english": "more", "portuguese": ["mais"]},
    {"english": "him", "portuguese": ["ele"]},
    {"english": "its", "portuguese": ["dele", "dela"]},
    {"english": "my", "portuguese": ["meu", "minha"]},
    {"english": "much", "portuguese": ["muito"]},
    {"english": "our", "portuguese": ["nosso", "nossa"]},
    {"english": "any", "portuguese": ["qualquer"]},
    {"english": "such", "portuguese": ["tanto", "tal"]},
    {"english": "every", "portuguese": ["cada", "todos", "todas"]},
    {"english": "many", "portuguese": ["muitos"]},
    
    {"english": "as", "portuguese": ["como"]},
    {"english": "of", "portuguese": ["de"]},
    {"english": "to", "portuguese": ["para"]},
    {"english": "in", "portuguese": ["em", "no", "na"]},
    {"english": "for", "portuguese": ["para"]},
    {"english": "on", "portuguese": ["em", "sobre", "no", "na", "ligado"]},
    {"english": "with", "portuguese": ["com"]},
    {"english": "at", "portuguese": ["em", "a"]},
    {"english": "from", "portuguese": ["de"]},
    {"english": "by", "portuguese": ["por", "pelo", "de", "pela"]},
    {"english": "about", "portuguese": ["sobre"]},
    {"english": "into", "portuguese": ["em"]},
    {"english": "after", "portuguese": ["depois", "após"]},
    {"english": "through", "portuguese": ["através"]},
    {"english": "before", "portuguese": ["antes"]},
    {"english": "under", "portuguese": ["debaixo", "sob", "abaixo de"]},
    {"english": "along", "portuguese": ["junto"]},
    {"english": "until", "portuguese": ["até"]},
    {"english": "without", "portuguese": ["sem"]},
    {"english": "between", "portuguese": ["entre"]},
    
    {"english": "and", "portuguese": ["e"]},
    {"english": "or", "portuguese": ["ou"]},
    {"english": "but", "portuguese": ["mas"]},
    {"english": "if", "portuguese": ["se"]},
    {"english": "than", "portuguese": ["que"]},
    {"english": "while", "portuguese": ["enquanto"]},
    
    {"english": "when", "portuguese": ["quando"]},
    {"english": "how", "portuguese": ["como"]},
    {"english": "up", "portuguese": ["para cima", "cima"]},
    {"english": "out", "portuguese": ["fora"]},
    {"english": "then", "portuguese": ["então", "depois"]},
    {"english": "so", "portuguese": ["tão", "então"]},
    {"english": "no", "portuguese": ["não"]},
    {"english": "not", "portuguese": ["não"]},
    {"english": "now", "portuguese": ["agora"]},
    {"english": "over", "portuguese": ["superior", "mais"]},
    {"english": "down", "portuguese": ["baixo"]},
    {"english": "only", "portuguese": ["apenas"]},
    {"english": "very", "portuguese": ["muito"]},
    {"english": "just", "portuguese": ["apenas", " justo", "só"]},
    {"english": "where", "portuguese": ["onde"]},
    {"english": "most", "portuguese": ["mais"]},
    {"english": "too", "portuguese": ["também"]},
    {"english": "also", "portuguese": ["também"]},
    {"english": "around", "portuguese": ["em torno de", "ao redor"]},
    {"english": "here", "portuguese": ["aqui"]},
    {"english": "why", "portuguese": ["por que"]},
    {"english": "away", "portuguese": ["distância", "longe", "distante"]},
    {"english": "again", "portuguese": ["novamente"]},
    {"english": "off", "portuguese": ["fora", "desligado"]},
    {"english": "still", "portuguese": ["ainda"]},
    {"english": "never", "portuguese": ["nunca"]},
    {"english": "below", "portuguese": ["abaixo"]},
    {"english": "always", "portuguese": ["sempre"]},
    {"english": "often", "portuguese": ["muitas vezes", "frequentemente"]},
    {"english": "together", "portuguese": ["juntos"]},
    {"english": "once", "portuguese": ["uma vez"]},
    {"english": "sometimes", "portuguese": ["as vezes"]},
    {"english": "above", "portuguese": ["acima", "superior"]},
    {"english": "almost", "portuguese": ["quase"]},
    {"english": "far", "portuguese": ["longe"]},
    {"english": "back", "portuguese": ["de volta", "voltar", "volta"]},
    
    {"english": "one", "portuguese": ["um"]},
    {"english": "two", "portuguese": ["dois"]},
    {"english": "three", "portuguese": ["três"]},
    {"english": "few", "portuguese": ["poucos", "alguns"]},
    {"english": "four", "portuguese": ["quatro"]},
    
    
    {"english": "actually", "portuguese": ["realmente", "na verdade", "de fato"]},
    {"english": "borrow", "portuguese": ["emprestar"]},
    {"english": "charge", "portuguese": ["cobrar", "cobrança"]},
    {"english": "content", "portuguese": ["conteúdo"]},
    {"english": "century", "portuguese": ["século"]},
    {"english": "college", "portuguese": ["faculdade"]},
    {"english": "cops", "portuguese": ["policiais", "policia", "policial"]},
    {"english": "fill", "portuguese": ["preencher"]},
    {"english": "library", "portuguese": ["biblioteca"]},
    {"english": "lunch", "portuguese": ["almoço"]},
    
    
    {"english": "accidental", "portuguese": ["acidental"]},
    {"english": "angel", "portuguese": ["anjo"]},
    {"english": "area", "portuguese": ["área"]},
    {"english": "banana", "portuguese": ["banana"]},
    {"english": "creation", "portuguese": ["criação"]},
    {"english": "comedy", "portuguese": ["comédia"]},
    {"english": "comic", "portuguese": ["cômico"]},
    {"english": "competition", "portuguese": ["competição"]},
    {"english": "correct", "portuguese": ["correto"]},
    {"english": "coffee", "portuguese": ["café"]},
    {"english": "chocolate", "portuguese": ["chocolate"]},
    {"english": "economy", "portuguese": ["economia"]},
    {"english": "elephant", "portuguese": ["elefante"]},
    {"english": "emotion", "portuguese": ["emoção"]},
    {"english": "example", "portuguese": ["exemplo"]},
    {"english": "future", "portuguese": ["futuro"]},
    {"english": "garage", "portuguese": ["garagem"]},
    {"english": "giraffe", "portuguese": ["girafa"]},
    {"english": "human", "portuguese": ["humano"]},
    {"english": "honest", "portuguese": ["honesto"]},
    {"english": "hour", "portuguese": ["hora"]},
    {"english": "moment", "portuguese": ["momento"]},
    {"english": "normal", "portuguese": ["normal"]},
    {"english": "object", "portuguese": ["objeto"]},
    {"english": "passport", "portuguese": ["passaporte"]},
    {"english": "patient", "portuguese": ["paciente"]},
    {"english": "present", "portuguese": ["presente"]},
    {"english": "positive", "portuguese": ["positivo"]},
    {"english": "potential", "portuguese": ["potencial"]},
    {"english": "offensive", "portuguese": ["ofensivo"]},
    {"english": "reaction", "portuguese": ["reação"]},
    {"english": "regular", "portuguese": ["regular"]},
    {"english": "simple", "portuguese": ["simples"]},
    {"english": "tomato", "portuguese": ["tomate"]},
    {"english": "vegetarian", "portuguese": ["vegetariano"]},
    {"english": "composition", "portuguese": ["composição"]},
    {"english": "idea", "portuguese": ["ideia"]},
    {"english": "minute", "portuguese": ["minuto"]},
    {"english": "mission", "portuguese": ["missão"]},
    {"english": "music", "portuguese": ["música", "musica"]},
    {"english": "persistent", "portuguese": ["persistente"]},
    {"english": "television", "portuguese": ["televisão"]},
    {"english": "material", "portuguese": ["material"]},
    {"english": "video", "portuguese": ["vídeo"]}
    ]